Improves keyboard navigation accessibility
RockefellerArchiveCenter/rockarch.org pull request #75
Opened 2020-05-04 21:08 UTC by HaSistrunk

- Changes strategy for main site navigation (using this [ARIA Authoring Practices example pattern](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html)) for better keyboard navigation options (using arrow keys, tab, and esc), and based on research on most commonly used a11y navigation patterns.
- Improves focus styles for keyboard navigation in main nav and side nav.
- Fixes #72 to add keyboard focus when not using a mobile device.

2020-05-05 14:59 UTC, helrond requested changes
Added one detailed comment but two other things:
1. when I've opened a menu using keyboard navigation, I am unable to close it and navigate to another top menu item. The spacebar scrolls, and the arrow keys seem boxed into the expanded menu items.
2. There's a weird styling thing happen with the open menus. I've tried flushing the cache, but to no avail.
<img width="483" alt="Screen Shot 2020-05-05 at 9 55 38 AM" src="https://user-images.githubusercontent.com/607621/81081099-1b83c000-8eb7-11ea-8a94-6970cc8d2336.png">

2020-05-05 14:59 UTC, helrond commented on _includes/scripts.html
>  <script src="{{ "/assets/js/inclusive-menu-button.min.js" | relative_url }}"></script>
Does the script you added replace the previous JS (inclusive-menu-button.min.js)? If so we can get rid of this script import (and the script that's imported)

2020-05-05 15:04 UTC, HaSistrunk commented on _includes/scripts.html
>  <script src="{{ "/assets/js/inclusive-menu-button.min.js" | relative_url }}"></script>
The script I added replaces the inclusive-button.min.js for the top nav, but the side nav is still using it (and I think it is probably more appropriate for the side nav).

2020-05-05 16:13 UTC, HaSistrunk commented
> when I've opened a menu using keyboard navigation, I am unable to close it and navigate to another top menu item. The spacebar scrolls, and the arrow keys seem boxed into the expanded menu items.

Yes, so I was reading through [the PR discussion for this pattern](https://github.com/w3c/aria-practices/pull/1036) leading to its addition as an example to the ARIA Authoring Practices. Originally there was no support for arrow keys, since the default for moving keyboard focus for screen reader use is `Tab / Shift + Tab`. However, the optional use of arrow keys to traverse open menu items was added for keyboard users who are not running a screen reader. `Esc` closes the menu and returns focus to the top-level button.

I can't find much info on user testing around these non-screenreader keyboard use patterns, but from my research on accessible link navigation with disclosure widgets, I like this pattern and it seems to be more widely used than using `role="menu"` for web page navigation (backed up by usa.gov, which uses a version of this without arrow key support).

2020-05-05 16:15 UTC, HaSistrunk commented
I _think_ I fixed the weird styling issue with the open menu with my last commit. Thanks for catching that!

2020-05-05 16:16 UTC, helrond commented on _includes/scripts.html
>  <script src="{{ "/assets/js/inclusive-menu-button.min.js" | relative_url }}"></script>
Hmmm, I'm not a huge fan of scripts with overlapping functionality which serve different parts of the page. The more stuff we load on a page the slower it is, and the more possibilities there are for conflicts. Is there a way we can use one script for both purposes?

2020-05-05 16:18 UTC, HaSistrunk commented on _includes/scripts.html
>  <script src="{{ "/assets/js/inclusive-menu-button.min.js" | relative_url }}"></script>
I think so, yes, but I was struggling some to understand how the side nav was working with the various scripts. I can revisit this.

2020-05-05 16:37 UTC, helrond commented on _includes/scripts.html
>  <script src="{{ "/assets/js/inclusive-menu-button.min.js" | relative_url }}"></script>
Great, I want to make sure we're not unnecessarily creating technical debt.

2020-05-05 16:44 UTC, helrond commented
This looks good to me! If we can get that issue with the scripts resolved I think this is good to go.

One thing I want to pay attention to on deployment is whether the new CSS styles get loaded in production without clearing the browser cache. If they don't we'll want to look at that and see if we can force that to happen somehow.

2021-03-24 20:00 UTC, HaSistrunk commented
> This looks good to me! If we can get that issue with the scripts resolved I think this is good to go.
> 
> One thing I want to pay attention to on deployment is whether the new CSS styles get loaded in production without clearing the browser cache. If they don't we'll want to look at that and see if we can force that to happen somehow.

OK! I've removed the `inclusive-menu-button.js` script and updated the existing scripts to use links instead of buttons on the side nav, which simplifies that some.

2021-03-24 20:56 UTC, helrond approved these changes

2021-03-24 20:59 UTC, merged